//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_Jue.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FotoPrenda
    {
        public int idFoto { get; set; }
        public string FotoPrenda1 { get; set; }
        public int idPrenda { get; set; }
    
        public virtual Prenda Prenda { get; set; }
    }
}
