//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_Jue.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prenda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prenda()
        {
            this.FotoPrendas = new HashSet<FotoPrenda>();
        }
    
        public int IdPrenda { get; set; }
        public string TipoPrenda { get; set; }
        public string Descripcion { get; set; }
        public float Valor { get; set; }
        public string Cliente { get; set; }
    
        public virtual Cliente Cliente1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FotoPrenda> FotoPrendas { get; set; }
    }
}
